### ISSUE TITLE
Loss values 

### ISSUE THREAD

**Issue by razihel96** [GuillaumeMougeot/DogFaceNet#9]
Hi, I have been studying your work for some time now (I'm doing a thesis about it) and would like to verify if the final results are consistent (I implemented a small script to print out some graphs for analysis).

Here are the results of your original code without any modifications:
![output accuracy](https://github.com/user-attachments/assets/5d814fb3-d284-42c8-90f7-ea181b615ac7)
![output loss](https://github.com/user-attachments/assets/b043050e-ac6d-4b80-a200-b09156df9055)
<img width="1280" alt="final result" src="https://github.com/user-attachments/assets/0d420081-e446-417e-82ba-bd075e91b5b7">

Even though the loss values do not fall within the typical 0.1 - 0.9 range, can they still be considered valid?

And here are the results after applying the following modifications:
•	I divided the output of the “triplet” function by 10 using the lambda function (in order to fall within the range 0.1 - 0.9)
•	I made the dataset more uniform by discarding classes with too few images
•	I set the batch size to 63 instead of 3*10

![output accuracy 2](https://github.com/user-attachments/assets/e7dc6fe4-ee5d-4936-b087-9bea5280ec99)
![output loss 2](https://github.com/user-attachments/assets/e89c20f4-7344-435a-8030-b0851fea1d10)
<img width="979" alt="final result 2" src="https://github.com/user-attachments/assets/f9109407-3abf-4bc4-83b4-dc07d436520e">

Does my modification make sense?

Thank you very much for your time. I look forward to hearing back from you.

**Comment by GuillaumeMougeot** [comment]
Hi,
sorry just saw your message,
Yes I think what you did make sense. But it seems that it affected your accuracy quite significantly (if we suppose that the two test set are identical in your examples). The loss not being between 0 and 1 is caused by the nature of its definition and should not be a problem, dividing it by ten should not change much of its performance. Changing the dataset and the batch size could make the comparison between before and after these modifications difficult because, on one side, of a potential difference in the two test sets and, on the other side, a larger batch size implies that the model will have seen more images per epochs. Just making sure that you had that in mind, if you did just forget about all of that.
good luck with your thesis!
